// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/95b7178e0ef33b4b88327676418b4cc3ad61df0f/leaflet-curve/leaflet-curve.d.ts
// Type definitions for leaflet-curve 0.0.1
// Project: https://github.com/onikiienko/Leaflet.curve
// Definitions by: Onikiienko <https://github.com/onikiienko>
// Definitions: https://github.com/DefinitelyTyped/DefinitelyTyped


declare module L {
	/**
	 * Drawing Bezier curves and other complex shapes.
	 */
	function  curve(path: any[], options?: L.PathOptions): Path;
}