// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/9f0f926a12026287b5a4a229e5672c01e7549313/node-uuid/node-uuid-cjs.d.ts
// Type definitions for node-uuid.js
// Project: https://github.com/broofa/node-uuid
// Definitions by: Jeff May <https://github.com/jeffmay>
// Definitions: https://github.com/borisyankov/DefinitelyTyped


/**
 * Expose as CommonJS module
 * For use in node environment or browser environment (using webpack or other module loaders)
 */
declare module "node-uuid" {
    var uuid: __NodeUUID.UUID;
    export = uuid;
}